### ISSUE TITLE
Request for reason_for_state_change

### ISSUE THREAD

**Issue by Alexkane** [gizmag/django-fsm-log#12]
Hi,
We're using django-fsm-log at Songtrust (thanks!) and I was wondering if you would be open to adding a reason_for_state_change field on the FSM log.  This would be helpful for us and we'd be willing to submit a patch for this if you're interested in incorporating it in the library.

Thanks
Alex Kane

**Comment by hzy** [comment]
Hi,

This has been briefly discussed before here https://github.com/gizmag/django-fsm-log/pull/5

Does the solution I mentioned there work for you?

If not, I am open to being convinced to add a `description` field in. What's your use case?

**Comment by Alexkane** [comment]
The solution you provided in tkt #5 doesn't work for us.  We're unable to derive the description from any combination of available properties.  We have an object with one of the transitions being from unreviewed to either approved or denied.  There are multiple reasons a denied transition can occur, some predefined and some entered at run time.

**Comment by Alexkane** [comment]
Just want to followup on this, are you willing to add this? If not we're going to have to create a fork.

**Comment by hzy** [comment]
I'm interested. would you go with the same approach as #5?

**Comment by Alexkane** [comment]
#5 works for me, yes

On Tue, Mar 31, 2015 at 10:03 PM, Jacob Haslehurst <notifications@github.com

**Comment by blueyed** [comment]
"description" was added in #67.

@Alexkane 
Does this work for you?
Otherwise `reason_for_state_change` could be added in a similar way probably now.

**Comment by Alexkane** [comment]
Yes I believe this will work, thanks!

**Comment by blueyed** [comment]
Great, closing this issue then.
