### ISSUE TITLE
New release on Pypi?

### ISSUE THREAD

**Issue by nanorepublica** [gizmag/django-fsm-log#28]
Hi 

Having merged #27 could you do a release please?

Thanks

**Comment by nanorepublica** [comment]
Any chance of this happening? It would be greatly appreciated!

**Comment by hzy** [comment]
I've been meaning to get around to this but haven't done it just yet. I'll try to do it this week

**Comment by nanorepublica** [comment]
Great! :smile:

**Comment by Bartvds** [comment]
+1 For a django 1.9 version on Pypi

**Comment by hzy** [comment]
`v1.3.0` has now been pushed up to PyPI https://github.com/gizmag/django-fsm-log/tree/v1.3.0
