### ISSUE TITLE
FSM_LOG doesn't track create state

### ISSUE THREAD

**Issue by Kianoosh76** [gizmag/django-fsm-log#36]
Hi!
Why the app doesn't create a StateLog object when the object is created?
Thanks for the wonderful app!

**Comment by ticosax** [comment]
What are you missing with the current behavior ?

**Comment by Kianoosh76** [comment]
I remember I wanted to keep a complete track for the object states and other information. The initial state of the object was also important for me.

**Comment by ticosax** [comment]
django-fsm-log is tracking `transitions`, creating an instance and initializing a state doesn't imply transitions. I'm reluctant to break this semantic. You could, in your project, rely on other mechanism like `signals` to achieve your goal. Thus I'm closing as `won't do`. Thanks for the proposal.
