### ISSUE TITLE
Not logging source state

### ISSUE THREAD

**Issue by jonasvp** [gizmag/django-fsm-log#37]
I'm not sure why the `target` state of the transition is logged but not the `source` state. The `target` can be inferred from the transition, since every transition can only have one target. The `source` is ambiguous, however, since it can be a list of states (https://github.com/kmmbvnr/django-fsm#usage).

I'll be happy to provide a pull request for saving the `source` to the `StateLog` model as well - or is there a reason it's currently not being logged?

**Comment by ticosax** [comment]
I agree with your analysis, let's fix this.
I'll help you having a PR merged.

**Comment by jonasvp** [comment]
Sorry, I missed the comment by @ticosax ! Pull request is here: https://github.com/gizmag/django-fsm-log/pull/75

**Comment by jonasvp** [comment]
Sorry, took me a while to figure out how to run the tests locally.

@ticosax The PR is now ready for review, the tests are passing and [coverage is up](https://codecov.io/gh/gizmag/django-fsm-log/pull/75) (the coverage report in the PR does not seem to update)

**Comment by blueyed** [comment]
Merged in 0480d7e, thanks!
