### ISSUE TITLE
Nested transitions with `@fsm_log_by` cause AttributeError

### ISSUE THREAD

**Issue by peterfarrell** [gizmag/django-fsm-log#38]
If you use nested transitions with Django FSM Admin and `@fsm_log_by` decorator on both transitions, an AttributeError is thrown because the `fsm_log_by` decorator on the inner transition calls `delattr(instance, 'by')` however when `fsm_log_by` decorate tries to delete the `by` attribute on the instance -- it fails with an AttributeError because it's already been deleted. In short, the `fsm_log_by` decorator deletes the `by` attribute in the instance prematurely when calling a transition from another transition within the same object.

We have fixed this in our own code base by writing a new decorator. Code to follow below. Would you accept a pull request for this? If so, let me know and we'll prepare a pull request.

``` python
from functools import wraps


def fsm_log_by(func):
    """
    Fixes issue with nested transitions and logging causes `instance.by` to be deleted too soon (in the nested inner
    transition and then tried to be deleted again in the outer transition.
    """

    @wraps(func)
    def wrapped(*args, **kwargs):
        arg_list = list(args)
        instance = arg_list.pop(0)
        by_set = False  # Track if this decorator was the one that set `by` in the instance

        if kwargs.get('by', None) and not hasattr(instance, 'by'):
            instance.by = kwargs['by']
            by_set = True

        out = func(instance, *arg_list, **kwargs)

        # Only delete the `by` if the function I decorate was the one that set `by` in the instance
        # Otherwise, the outer transition will take care of cleaning things up
        if hasattr(instance, 'by') and by_set:
            delattr(instance, 'by')

        return out

    return wrapped
```

**Comment by ticosax** [comment]
Can you explain what are nested transitions and how you design your state machine ?
It seems to me that your model will always end up in the target state of the outer transition, no matter what, and that inner transitions are just side effects and doesn't have to be a transition.

**Comment by ticosax** [comment]
I'll try by the end of this week.
