### ISSUE TITLE
Django admin inline for fsm-log sample

### ISSUE THREAD

**Issue by Sovetnikov** [gizmag/django-fsm-log#43]
Just if someone interested to show FMS state changes as admin inline, here is working prototype for Django 1.7.7:
https://gist.github.com/Sovetnikov/ebd27eb1d783f9d66a205ac139f9f14b

**Comment by ticosax** [comment]
Thanks, this would be useful. Are you interested to make a pull request ?

**Comment by ticosax** [comment]
Hi @Sovetnikov ,
Thank you for your proposal, I quite like it. Since I've been granted committer rights for this project, I'd like to inform you that I will be supportive of integrating your proposal. Are you willing to make a pull request ?

**Comment by Sovetnikov** [comment]
@ticosax, i just have no time to check and adapt my solution with Django >=1.8
I'm glad if it helps you
