### ISSUE TITLE
Would you like to transfer ownership ?

### ISSUE THREAD

**Issue by ticosax** [gizmag/django-fsm-log#47]
I'd like to take it over, then I'll organize the move to [jazzband](https://jazzband.co/)

**Comment by browniebroke** [comment]
@jacobh are you able to work this out? What happened to the gizmag organisation? It seems it's now [New Atlas](https://twitter.com/gizmag/status/760231253295501313)...

**Comment by jacobh** [comment]
Hi, I no longer have admin access to this repository. @tysonclugg would you be able to help moving this repo to jazzband?

**Comment by tysonclugg** [comment]
Thanks very much for the offer to help out!

I've just created the @gizmag/django-fsm-log team with admin rights, and invited @ticosax and @jacobh to join it.  I'd appreciate if the @gizmag/gizmag-development team can retain admin rights to make improvements as @gizmag might need from time to time.

I'm +1 on adopting the code of conduct and other requirements of projects in the @jazzband organization, but -0.5 with this project moving to @jazzband given that you now have admin rights anyway.  Moving the project would be little more than a name change, and somewhat unnecessary.  However, I'll leave that decision to @jacobh and @ticosax.

I'm closing this issue as you now have admin rights.

FYI @browniebroke: Gizmag (the organization) still exists, the online publication was renamed (to New Atlas).

**Comment by browniebroke** [comment]
Cool! Thanks for the update and making things move. Let me know if I can help with anything @ticosax

**Comment by ticosax** [comment]
Thank you for your trust @tysonclugg, I'll do my best to keep this project up to date.
One more thing regarding publishing releases to Pypi, do you want to do it or you'd prefer hand it out to us as well ?
If you decide to invite us, my identifier is [nicolas_delaby](https://pypi.python.org/pypi/nicolas_delaby)

**Comment by jacobh** [comment]
I've added you as a "maintainer" on PyPI @ticosax :) Thanks for taking this over! I'm quite proud of this project, but haven't had use or interest in it over the last couple of years :)
