### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by blueyed** [gizmag/django-fsm-log#79]
@ticosax 
Do you want to do it?
Or can you give me permissions on PyPI?
/cc @gizmag

**Comment by ticosax** [comment]
I don't have the permission @blueyed .

**Comment by tysonclugg** [comment]
@ticosax is now an owner of the project on PyPi, and @blueyed is now a maintainer.  You're welcome.  :-)

**Comment by tysonclugg** [comment]
For the record, @ticosax was given maintainer permissions some time ago.

**Comment by ticosax** [comment]
Thanks @tysonclugg ! @blueyed let me know if you need more help

**Comment by blueyed** [comment]
Thanks.
@ticosax 
Would be good if you could cut a release - might take me some time to do it myself.  But I can understand if you're also lacking time/motivation.

**Comment by ticosax** [comment]
https://pypi.org/project/django-fsm-log/1.6.0/

**Comment by blueyed** [comment]
Thank you!
