### ISSUE TITLE
Allow manager to be used in migrations

### ISSUE THREAD

**Issue by imomaliev** [gizmag/django-fsm-log#94]
Hi, I would like to have ability to use `StateLog`'s manager in migrations for data migrations 

https://docs.djangoproject.com/en/2.1/topics/migrations/#model-managers

I could provide PR if this feature request accepted

**Comment by blueyed** [comment]
Sounds good to me in general.
What is your use case?

**Comment by imomaliev** [comment]
I have 2 models, parent and child, child model has fsm. I need to add fsm functionality to parent one. So for the sake of data consistency I need to do data migration and create `StateLog` records for existing objects of parent model based on state logs of the child.
