### ISSUE TITLE
Support Django 3

### ISSUE THREAD

**Issue by jodal** [gizmag/django-fsm-log#98]
Django 3 is to be released next week.

django-fsm does not yet support Django 3, but there's not that large changes needed, and there is a working fork, so support in django-fsm-log is useful even if django-fsm isn't updated.

To get django-fsm-log working with Django 3 is mostly a matter of stop using Django's private Python 2 compat APIs, https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis, e.g. `django.utils.six`.

**Comment by jodal** [comment]
Django 3 is now out and django-fsm 2.7.0 has been released with Django 3 support.

**Comment by moseb** [comment]
This line with `django.utils.encoding.python_2_unicode_compatible` is also breaking with Django 3:
https://github.com/gizmag/django-fsm-log/blob/355cb226534cd31c7cdbf76fb7b25526d922c42c/django_fsm_log/models.py#L7

**Comment by clovis1122** [comment]
BUMP. Was this released? I cannot find the next version on pip: https://pypi.org/project/django-fsm-log/#history

**Comment by jodal** [comment]
With the merge of #99, this can be closed.
